on: [pull_request]

jobs:
  pylint_job:
    runs-on: ubuntu-latest
    name: A job to run pylint action
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'decisionengine'
      id: checkout
    - name: Cache venv
      uses: actions/cache@v1
      with:
        path: ./venv
        key: ${{ runner.os }}-venv
        restore-keys: |
          ${{ runner.os }}-venv
          ${{ runner.os }}-
    - name: pylint action step
      uses: ./.github/actions/pylint-in-sl7-docker
      id: pylint
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: logs.tar.bz2
